server:
  port: 80
spring:
  application:
    name: cloud-consumer-order
  cloud:
    # consul配置类
    consul:
      host: 192.168.81.131
      port: 8500
      discovery:
        service-name: ${spring.application.name}
