server:
  port: 80
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka1:7001/eureka,http://eureka2:7002/eureka
spring:
  application:
    name: cloud-order-service
  zipkin:
    base-url: http://192.168.81.131:9411/
  sleuth:
    sampler:
      probability: 1