server:
  port: 8401
spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.81.131:8848/
    sentinel:
      transport:
        # 配置sentinel dashboard地址
        dashboard: 192.168.81.131:8858
        # 默认8719端口，假如被占用就自动从8719开始依次+1扫描，直到未被占用的端口
        port: 8719
management:
  endpoints:
    web:
      exposure:
        include: '*'